### ISSUE TITLE
Tessellation shaders

### ISSUE THREAD

**Issue by John-Colvin** [Dav1dde/glamour#19]
any chance of support for them in glamour.shader?

**Comment by Dav1dde** [comment]
They need to be added there: https://github.com/Dav1dde/glamour/blob/master/glamour/shader.d#L40-L48

The problem is, not all supported gl bindings do actually export the enums: https://github.com/Dav1dde/glamour/blob/master/glamour/shader.d#L6

So, I am not sure what the best way to solve the problem is.

**Comment by John-Colvin** [comment]
https://github.com/Dav1dde/glamour/pull/20
